version: 2
registries:
  docker-registry-registry-hub-docker-com:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: lifendependabot
    password: "${{secrets.DOCKER_REGISTRY_REGISTRY_HUB_DOCKER_COM_PASSWORD}}"

updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Europe/Paris
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.38.20
    - 1.38.21
    - 1.38.22
    - 1.38.23
    - 1.38.24
    - 1.38.25
    - 1.38.26
    - 1.38.27
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Europe/Paris
  registries:
  - docker-registry-registry-hub-docker-com
